//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tSeracherr.WPF.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tSeracherr.WPF.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертуй.
        /// </summary>
        public static string ConvertUC_Btn_Convert {
            get {
                return ResourceManager.GetString("ConvertUC_Btn_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертація.
        /// </summary>
        public static string ConvertUC_TextBlock_Convert {
            get {
                return ResourceManager.GetString("ConvertUC_TextBlock_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В що конвертуємо.
        /// </summary>
        public static string ConvertUC_TextBlock_ConvertTo {
            get {
                return ResourceManager.GetString("ConvertUC_TextBlock_ConvertTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертовані токени.
        /// </summary>
        public static string ConvertUC_TextBlock_ConvertToken {
            get {
                return ResourceManager.GetString("ConvertUC_TextBlock_ConvertToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Що конвертуємо.
        /// </summary>
        public static string ConvertUC_TextBlock_WhatConvert {
            get {
                return ResourceManager.GetString("ConvertUC_TextBlock_WhatConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введи перший токен..
        /// </summary>
        public static string ConvertVM_EntrFirstTkn {
            get {
                return ResourceManager.GetString("ConvertVM_EntrFirstTkn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введи другий токен..
        /// </summary>
        public static string ConvertVM_EntrScndTkn {
            get {
                return ResourceManager.GetString("ConvertVM_EntrScndTkn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не знайдено..
        /// </summary>
        public static string ErrorMSG_WasntFound {
            get {
                return ResourceManager.GetString("ErrorMSG_WasntFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        public static string HomeUC_TextBlock_Home {
            get {
                return ResourceManager.GetString("HomeUC_TextBlock_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ 10 токенів.
        /// </summary>
        public static string HomeUC_TextBlock_Top {
            get {
                return ResourceManager.GetString("HomeUC_TextBlock_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темна.
        /// </summary>
        public static string OptionsUC_Btn_Dark {
            get {
                return ResourceManager.GetString("OptionsUC_Btn_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Англ.
        /// </summary>
        public static string OptionsUC_Btn_Eng {
            get {
                return ResourceManager.GetString("OptionsUC_Btn_Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Світла.
        /// </summary>
        public static string OptionsUC_Btn_Light {
            get {
                return ResourceManager.GetString("OptionsUC_Btn_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укр.
        /// </summary>
        public static string OptionsUC_Btn_Ukr {
            get {
                return ResourceManager.GetString("OptionsUC_Btn_Ukr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string OptionsUC_TextBlock_Languages {
            get {
                return ResourceManager.GetString("OptionsUC_TextBlock_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теми.
        /// </summary>
        public static string OptionsUC_TextBlock_Theme {
            get {
                return ResourceManager.GetString("OptionsUC_TextBlock_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук.
        /// </summary>
        public static string SearchUC_Btn_Search {
            get {
                return ResourceManager.GetString("SearchUC_Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву токена для пошуку.
        /// </summary>
        public static string SearchUC_TextBlock_EnterTokenForSearch {
            get {
                return ResourceManager.GetString("SearchUC_TextBlock_EnterTokenForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук.
        /// </summary>
        public static string SearchUC_TextBlock_Search {
            get {
                return ResourceManager.GetString("SearchUC_TextBlock_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву токена..
        /// </summary>
        public static string SearchVM_EntrTknName {
            get {
                return ResourceManager.GetString("SearchVM_EntrTknName", resourceCulture);
            }
        }
    }
}
